---
# tasks file for roles/ingress
- name: Verificar Traefik
  shell: kubectl get pods -n kube-system | grep traefik
  register: traefik_check
  ignore_errors: yes

- name: Mostrar estado Traefik
  debug:
    var: traefik_check.stdout

- name: Crear ingress Grafana
  shell: |
    kubectl apply -f ../kubernetes/ingress/grafana-ingress.yaml

- name: Crear ingress Prometheus
  shell: |
    kubectl apply -f ../kubernetes/ingress/prometheus-ingress.yaml

- name: Verificar ingress
  shell: kubectl get ingress -A
  register: ingress_status

- name: Mostrar ingress
  debug:
    var: ingress_status.stdout
