---
# tasks file for ansible/roles/logging
- name: Añadir repo
  shell: |
    helm repo add grafana https://grafana.github.io/helm-charts

- name: Actualizar repo
  shell: |
    helm repo update

- name: Verificar Loki
  shell: |
    kubectl get pods -n logging
  register: loki_check
  ignore_errors: yes

- name: Instalar Loki Stack
  shell: |
    helm install loki grafana/loki-stack -n logging --create-namespace -f ../kubernetes/logging/loki-values.yaml
  when: loki_check.rc ==0
