---
# tasks file for roles/docker
- name: Verificar Docker
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Descargar llave GPG de Docker
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  when: docker_check.failed

- name: Añadir repositorio de Docker
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: docker_check.failed

- name: Instalar dependencias Docker y actualizar repositorios
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes
  become: yes
  when: docker_check.failed

- name: Instalar Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes
  when: docker_check.failed

- name: Iniciar Docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
  when: docker_check.failed
